### ISSUE TITLE
MRD library is now GJB Library

### ISSUE THREAD

**Issue by achyu-dev** [silicoflare/pesupedia#2]
Under 

# Notable Locations in and around RR Campus
```MRD library``` should be removed.

The MRD library is no more in MRD Block. It is there in GJB now, and called GJB library. 

Suggested content under ```#The GJB Block``` - 

> ## GJB library
> 
> It is on the first floor of the Golden Jubilee Block, and has a large collection of academic books, and an e-library too. You can borrow textbooks from here, or read them in the library.

**Comment by achyu-dev** [comment]
This change is still not done

**Comment by silicoflare** [comment]
@achyu2003 it is fixed in the latest deployment
https://pesupedia.vercel.app/rr-campus/#gjb-library

**Comment by achyu-dev** [comment]
Great ! Thank you
