### ISSUE TITLE
There is a bug in SGPA calculator

### ISSUE THREAD

**Issue by Yashas-naidu** [silicoflare/pesupedia#4]
Whenever you try adding new subjects you are not able to change those grades neither increase or decrease and Grade points are always set to 0 try fixing those 

![Screenshot 2024-05-20 200914](https://github.com/silicoflare/pesupedia/assets/116648558/a998bdce-ee6a-4d68-a854-bdb02b2d943c)

**Comment by silicoflare** [comment]
@Yashas-naidu i fixed it now, please do check
